
test:2.7:
  image: python:2.7
  script:
  - python setup.py test

test:3.4:
  image: python:3.4
  script:
  - python setup.py test

test:3.5:
  image: python:3.5
  script:
  - python setup.py test

test:3.6:
  image: python:3.6
  script:
  - python setup.py test

pages:
  stage: deploy
  image: python:2.7
  before_script:
  - apt-get update
  - apt-get install -y nodejs npm
  - ln -s /usr/bin/nodejs /usr/bin/node
  script:
  - python setup.py docs_build
  - rm -rf public
  - mv _book public
  artifacts:
    paths:
    - public
  only:
  - 136-convert-edmunds-to-python
