
test:2.7:
  image: python:2.7
  script:
  - python setup.py test

test:3.4:
  image: python:3.4
  script:
  - python setup.py test

test:3.5:
  image: python:3.5
  script:
  - python setup.py test

test:3.6:
  image: python:3.6
  script:
  - python setup.py test

pages:
  stage: deploy
  script:
  - python setup.py docs_build
  artifacts:
    paths:
    - _book
  only:
  - 136-convert-edmunds-to-python
