
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"


install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run --source=edmunds setup.py test
after_success:
  - coveralls


before_deploy:
  - python setup.py docs_build
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: _book
    on:
      branch: master
      python: "3.6"


notifications:
  slack:
    rooms:
      - secure: Pp8bSLo/pDG/dzX7w8IS9n13lXPgHNDlsguA+b3AWbUH8BMb5VmM/6tZUMdOft8Bi7p/PsAchuRf1nnqL/VHTc1oGd5qvRXR5NR2rVIJigAzJIuaIi9r/3rbET4hIdHllacEknCuKwHDxqx4GsAW/4Rlrog90OOoJghU2VccymgLfEQNXse4f293WWa0W/MM3gNzqCUTemBGw/LsFwasrgEWtMsfynD8mKO8Y9mkLiMHh1tRu6NFpsyUUmNoA2dERIkBQE1UxyixwOCiZFTsvIEhKOUhPxsReKxQvvebf6xP+MCJqN/fNLsP2AKd7Dk0RgMATUYUYNhYtkKMd99GSgzT/E32Ubf8dEByLcaSeAkGIrL4nGNcUiQAQkXAfj0fvRyzhe3kV1KaZft7qHhXBL85XSctu9fzDz7Q+t4fwbx12ht4cVYYxtdl6RsmlQoX4RUtVgH7qKDFcrJS0JeMnpmFvzSykYsFQxM+2rh9mLlrKzi9iqsuP5yaEesk3Eb/HMqHwYdyITk/tE+rmiDI3ImFcUsaiopt1gzVkeBpK3CUC0Rrgh9U2Gq9He7lZU4KfsznxHz8KlK7D9smEKVnEruM1U8YT7iwPbanYei1HoyAcOtVkZ+wyDtuEqRQLEyo82+mBpvGaKLBWBGrIox7nvpvW4IpXlr37xRo2eyIw4o=
    on_success: change
    on_failure: always
  email: false
