version: 2

jobs:

  test-2.7:
      docker:
        - image: lowieh/docker-python-gcp:2.7
      steps:
        - checkout
        - restore_cache:
            key: deps-test-2.7-{{ .Branch }}-{{ checksum "requirements.txt" }}
        - run:
            command: |
              python -m virtualenv venv
              . venv/bin/activate
              pip install -r requirements.txt
        - save_cache:
            key: deps-test-2.7-{{ .Branch }}-{{ checksum "requirements.txt" }}
            paths:
              - "venv"
        - run:
            command: |
              . venv/bin/activate
              coverage run --append --source=app setup.py test

  test-3.6:
      docker:
        - image: lowieh/docker-python-gcp:3.6
      steps:
        - checkout
        - restore_cache:
            key: deps-test-3.6-{{ .Branch }}-{{ checksum "requirements.txt" }}
        - run:
            command: |
              python -m venv venv
              . venv/bin/activate
              pip install -r requirements.txt
        - save_cache:
            key: deps-test-3.6-{{ .Branch }}-{{ checksum "requirements.txt" }}
            paths:
              - "venv"
        - run:
            command: |
              . venv/bin/activate
              coverage run --append --source=app setup.py test

  codecov:
      docker:
        - image: lowieh/docker-python-gcp:3.6
      steps:
        - run: pip install codecov
        - run: codecov


workflows:
  version: 2

  test-2.7:
    jobs:
      - test-2.7

  test-3.6:
    jobs:
      - test-3.6
